<?php
header('Content-Type: application/json');
require_once '../config.php';
require_once __DIR__ . '/middleware.php';
requireAdmin();
$action=$_GET['action']??$_POST['action']??'';
switch($action){case 'stats':getStats();break;case 'orders':getOrders();break;case 'products':getProducts();break;case 'customers':getCustomers();break;case 'messages':getMessages();break;case 'update_order_status':updateOrderStatus();break;default:sendResponse(false,'Invalid action');}
function getStats(){global $conn;$s=[];$r=$conn->query("SELECT COUNT(*) total FROM orders");$s['total_orders']=$r->fetch_assoc()['total'];$r=$conn->query("SELECT COUNT(*) total FROM orders WHERE status='pending'");$s['pending_orders']=$r->fetch_assoc()['total'];$r=$conn->query("SELECT COALESCE(SUM(total),0) revenue FROM orders WHERE status!='cancelled'");$s['total_revenue']=(float)$r->fetch_assoc()['revenue'];$r=$conn->query("SELECT COUNT(*) total FROM customers");$s['total_customers']=$r->fetch_assoc()['total'];sendResponse(true,'Stats retrieved',['stats'=>$s]);}
function getOrders(){global $conn;$limit=max(1,min(100,(int)($_GET['limit']??50)));$offset=max(0,(int)($_GET['offset']??0));$st=$conn->prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT ? OFFSET ?');$st->bind_param('ii',$limit,$offset);$st->execute();$r=$st->get_result();$a=[];while($row=$r->fetch_assoc())$a[]=$row;sendResponse(true,'Orders retrieved',['orders'=>$a]);}
function getProducts(){global $conn;$r=$conn->query('SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON p.category_id=c.id ORDER BY p.id DESC');$a=[];while($row=$r->fetch_assoc())$a[]=$row;sendResponse(true,'Products retrieved',['products'=>$a]);}
function getCustomers(){global $conn;$r=$conn->query('SELECT id,email,phone,first_name,last_name,address,city,state,role,last_login,created_at FROM customers ORDER BY created_at DESC');$a=[];while($row=$r->fetch_assoc())$a[]=$row;sendResponse(true,'Customers retrieved',['customers'=>$a]);}
function getMessages(){global $conn;$r=$conn->query('SELECT * FROM contact_messages ORDER BY created_at DESC');$a=[];while($row=$r->fetch_assoc())$a[]=$row;sendResponse(true,'Messages retrieved',['messages'=>$a]);}
function updateOrderStatus(){global $conn;$id=trim($_POST['order_id']??'');$status=trim($_POST['status']??'');$valid=['pending','processing','shipped','delivered','cancelled'];if(!$id||!in_array($status,$valid,true))sendResponse(false,'Invalid order or status');$st=$conn->prepare('UPDATE orders SET status=?,updated_at=NOW() WHERE order_id=?');$st->bind_param('ss',$status,$id);if(!$st->execute())sendResponse(false,'Failed to update order');sendResponse(true,'Order status updated');}
function sendResponse($success,$message,$data=[]){echo json_encode(['success'=>$success,'message'=>$message,'data'=>$data]);exit;}
?>