<?php
header('Content-Type: application/json');
require_once '../config.php';
require_once __DIR__ . '/middleware.php';
$action=$_GET['action']??$_POST['action']??'';
if(in_array($action,['get_all_orders','get_orders_by_status'],true)) requireAdmin(); else requireLogin();
switch($action){case 'get_order':getOrder();break;case 'get_orders_by_email':getOrdersByEmail();break;case 'get_all_orders':getAllOrders();break;case 'get_order_items':getOrderItems();break;case 'get_orders_by_status':getOrdersByStatus();break;default:sendResponse(false,'Invalid action');}
function getOrder(){global $conn;$id=trim($_GET['order_id']??'');if(!$id)sendResponse(false,'Order ID is required');$admin=isAdmin();$customerId=$admin?0:requireLogin();$st=$conn->prepare('SELECT * FROM orders WHERE order_id=? LIMIT 1');$st->bind_param('s',$id);$st->execute();$r=$st->get_result();if(!$r->num_rows)sendResponse(false,'Order not found');$order=$r->fetch_assoc();if(!$admin&&getCustomerEmail($customerId)!==$order['email'])sendResponse(false,'Access denied');$order['items']=getItems($id);sendResponse(true,'Order retrieved successfully',['order'=>$order]);}
function getOrdersByEmail(){global $conn;$customerId=requireLogin();$email=getCustomerEmail($customerId);$st=$conn->prepare('SELECT * FROM orders WHERE email=? ORDER BY created_at DESC');$st->bind_param('s',$email);$st->execute();$r=$st->get_result();$a=[];while($o=$r->fetch_assoc()){$o['item_count']=count(getItems($o['order_id']));$a[]=$o;}sendResponse(true,'Orders retrieved successfully',['orders'=>$a]);}
function getAllOrders(){global $conn;$page=max(1,(int)($_GET['page']??1));$limit=max(1,min(100,(int)($_GET['limit']??20)));$offset=($page-1)*$limit;$total=(int)$conn->query('SELECT COUNT(*) total FROM orders')->fetch_assoc()['total'];$st=$conn->prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT ? OFFSET ?');$st->bind_param('ii',$limit,$offset);$st->execute();$r=$st->get_result();$a=[];while($o=$r->fetch_assoc()){$o['item_count']=count(getItems($o['order_id']));$a[]=$o;}sendResponse(true,'Orders retrieved successfully',['orders'=>$a,'pagination'=>['current_page'=>$page,'total_pages'=>$limit?ceil($total/$limit):0,'total_orders'=>$total,'orders_per_page'=>$limit]]);}
function getOrderItems(){global $conn;$id=trim($_GET['order_id']??'');if(!$id)sendResponse(false,'Order ID is required');$admin=isAdmin();$customerId=$admin?0:requireLogin();$st=$conn->prepare('SELECT email FROM orders WHERE order_id=? LIMIT 1');$st->bind_param('s',$id);$st->execute();$r=$st->get_result();if(!$r->num_rows)sendResponse(false,'Order not found');$email=$r->fetch_assoc()['email'];if(!$admin&&getCustomerEmail($customerId)!==$email)sendResponse(false,'Access denied');sendResponse(true,'Order items retrieved successfully',['items'=>getItems($id)]);}
function getOrdersByStatus(){global $conn;$status=trim($_GET['status']??'');$valid=['pending','processing','shipped','delivered','cancelled'];if(!in_array($status,$valid,true))sendResponse(false,'Invalid or missing status');$st=$conn->prepare('SELECT * FROM orders WHERE status=? ORDER BY created_at DESC');$st->bind_param('s',$status);$st->execute();$r=$st->get_result();$a=[];while($o=$r->fetch_assoc())$a[]=$o;sendResponse(true,'Orders retrieved successfully',['status'=>$status,'orders'=>$a,'count'=>count($a)]);}
function getItems($id){global $conn;$st=$conn->prepare('SELECT * FROM order_items WHERE order_id=? ORDER BY created_at ASC');$st->bind_param('s',$id);$st->execute();$r=$st->get_result();$a=[];while($x=$r->fetch_assoc())$a[]=$x;return $a;}
function getCustomerEmail($id){global $conn;$st=$conn->prepare('SELECT email FROM customers WHERE id=? LIMIT 1');$st->bind_param('i',$id);$st->execute();$r=$st->get_result();if(!$r->num_rows)sendResponse(false,'Customer account not found');return $r->fetch_assoc()['email'];}
function sendResponse($success,$message,$data=[]){echo json_encode(['success'=>$success,'message'=>$message,'data'=>$data,'timestamp'=>date('Y-m-d H:i:s')]);exit;}
?>