<?php
header('Content-Type: application/json');
require_once '../config.php';
require_once __DIR__ . '/middleware.php';
requireAdmin();
$action=$_POST['action']??'';
switch($action){case 'update_status':updateOrderStatus();break;case 'update_notes':updateOrderNotes();break;case 'cancel_order':cancelOrder();break;case 'delete_order':deleteOrder();break;default:sendResponse(false,'Invalid action');}
function updateOrderStatus(){global $conn;$id=trim($_POST['order_id']??'');$status=trim($_POST['status']??'');$valid=['pending','processing','shipped','delivered','cancelled'];if(!$id)sendResponse(false,'Order ID is required');if(!in_array($status,$valid,true))sendResponse(false,'Invalid status');$st=$conn->prepare('UPDATE orders SET status=?,updated_at=NOW() WHERE order_id=?');$st->bind_param('ss',$status,$id);if(!$st->execute()||$st->affected_rows<1)sendResponse(false,'Order not found or unchanged');sendResponse(true,'Order status updated successfully',['order_id'=>$id,'new_status'=>$status]);}
function updateOrderNotes(){global $conn;$id=trim($_POST['order_id']??'');$notes=trim($_POST['notes']??'');if(!$id)sendResponse(false,'Order ID is required');$st=$conn->prepare('UPDATE orders SET notes=?,updated_at=NOW() WHERE order_id=?');$st->bind_param('ss',$notes,$id);if(!$st->execute()||$st->affected_rows<1)sendResponse(false,'Order not found or unchanged');sendResponse(true,'Order notes updated successfully',['order_id'=>$id,'notes'=>$notes]);}
function cancelOrder(){global $conn;$id=trim($_POST['order_id']??'');if(!$id)sendResponse(false,'Order ID is required');$st=$conn->prepare("UPDATE orders SET status='cancelled',updated_at=NOW() WHERE order_id=? AND status NOT IN ('cancelled','delivered')");$st->bind_param('s',$id);if(!$st->execute()||$st->affected_rows<1)sendResponse(false,'Order not found or cannot be cancelled');sendResponse(true,'Order cancelled successfully',['order_id'=>$id,'status'=>'cancelled']);}
function deleteOrder(){global $conn;$id=trim($_POST['order_id']??'');if(!$id)sendResponse(false,'Order ID is required');$conn->begin_transaction();try{$st=$conn->prepare("SELECT status FROM orders WHERE order_id=? FOR UPDATE");$st->bind_param('s',$id);$st->execute();$r=$st->get_result();if(!$r->num_rows)throw new Exception('Order not found');if($r->fetch_assoc()['status']!=='pending')throw new Exception('Can only delete pending orders');$st=$conn->prepare('DELETE FROM order_items WHERE order_id=?');$st->bind_param('s',$id);$st->execute();$st=$conn->prepare('DELETE FROM orders WHERE order_id=?');$st->bind_param('s',$id);$st->execute();$conn->commit();sendResponse(true,'Order deleted successfully',['order_id'=>$id]);}catch(Exception $e){$conn->rollback();sendResponse(false,$e->getMessage());}}
function sendResponse($success,$message,$data=[]){echo json_encode(['success'=>$success,'message'=>$message,'data'=>$data,'timestamp'=>date('Y-m-d H:i:s')]);exit;}
?>